# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rcli}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Eduardo Del Balso"]
  s.date = %q{2010-11-09}
  s.default_executable = %q{rcli}
  s.description = %q{This script creates, manages, installs, uninstalls and edits command-line ruby scripts. It also works as a useful library for building scripts.}
  s.email = %q{e.delbalso@gmail.com}
  s.executables = ["rcli"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "LICENSE",
     "README.rdoc",
     "Rakefile",
     "lib/commands/compile.rb",
     "lib/commands/debug.rb",
     "lib/commands/edit.rb",
     "lib/commands/generate.rb",
     "lib/commands/help.rb",
     "lib/commands/install.rb",
     "lib/commands/list.rb",
     "lib/commands/uninstall.rb",
     "lib/commands/version.rb",
     "lib/config/application.yml",
     "lib/core/actions.rb",
     "lib/core/actions/create_file.rb",
     "lib/core/actions/empty_directory.rb",
     "lib/core/actions/file_binary_read.rb",
     "lib/core/command.rb",
     "lib/core/commander.rb",
     "lib/core/console.rb",
     "lib/core/global_functions.rb",
     "lib/core/shared/rcli_installation.rb",
     "lib/core/thor_actions.rb",
     "lib/core/thor_actions/create_file.rb",
     "lib/core/thor_actions/directory.rb",
     "lib/core/thor_actions/empty_directory.rb",
     "lib/core/thor_actions/file_binary_read.rb",
     "lib/core/thor_actions/file_manipulation.rb",
     "lib/core/thor_actions/inject_into_file.rb",
     "lib/core/traceable_factory.rb",
     "lib/core/traceable_object.rb",
     "lib/core/tracer.rb",
     "lib/rcli.rb",
     "lib/templates/new_app/RCLIAPPNAME.rb",
     "lib/templates/new_app/lib/commands/default.rb",
     "lib/templates/new_app/lib/commands/version.rb",
     "lib/vendor/mainline/lib/trollop.rb",
     "lib/vendor/mainline/test/test_trollop.rb",
     "lib/vendor/trollop.rb",
     "test/helper.rb",
     "test/test_rcli-gem.rb"
  ]
  s.homepage = %q{http://github.com/edelbalso/rcli}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A rough framework for building command-line scripts in ruby.}
  s.test_files = [
    "test/helper.rb",
     "test/test_rcli-gem.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<text>, [">= 0.2.0"])
      s.add_runtime_dependency(%q<highline>, [">= 1.6.1"])
    else
      s.add_dependency(%q<text>, [">= 0.2.0"])
      s.add_dependency(%q<highline>, [">= 1.6.1"])
    end
  else
    s.add_dependency(%q<text>, [">= 0.2.0"])
    s.add_dependency(%q<highline>, [">= 1.6.1"])
  end
end

